---
abstract: 'Merge blank nodes that obviously refer to the same resource'
author:
  - 'Jakob Voß'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RDF-TrineX-Merge-Bnodes
resources:
  bugtracker: https://github.com/nichtich/RDF-TrineX-Merge-Bnodes/issues
  homepage: https://github.com/nichtich/RDF-TrineX-Merge-Bnodes
  repository: https://github.com/nichtich/RDF-TrineX-Merge-Bnodes.git
version: 0.1.0
